In [89]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import *

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#import matplotlib.pyplot as plt
#%matplotlib inline


In [63]:
from sklearn.datasets import load_iris

dataset = load_iris()

features = dataset.feature_names
train = pd.DataFrame(dataset.data, columns=features)
target = dataset.target

train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [64]:
data_scaler = MinMaxScaler(feature_range=(0,1))

train_fit = pd.DataFrame(data_scaler.fit_transform(train), columns=features)

train_fit

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [135]:
X = train_fit
y = target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [136]:
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
dtc_pred = y_pred

result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)


Confusion Matrix:
[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

Accuracy: 0.9555555555555556


In [137]:
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
rfc_pred = y_pred


print("Features Importance:")
for i in range(len(features)):
    print(str(features[i]) + ' : ' + str(clf.feature_importances_[i]))

result = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(result)

result1 = classification_report(y_test, y_pred)
print("\nClassification Report:",)
print (result1)

result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)


Features Importance:
sepal length (cm) : 0.08195611587240585
sepal width (cm) : 0.031828771483063706
petal length (cm) : 0.46380444186286846
petal width (cm) : 0.42241067078166206

Confusion Matrix:
[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

Accuracy: 0.9555555555555556


In [138]:
clf = KNeighborsClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
knc_pred = y_pred


result = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(result)

result1 = classification_report(y_test, y_pred)
print("\nClassification Report:",)
print (result1)

result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)



Confusion Matrix:
[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

Accuracy: 0.9555555555555556


In [140]:
# https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html

avg_pred = []
for i in range(len(dtc_pred)):
    tmp = [dtc_pred[i], rfc_pred[i], knc_pred[i]]
    
    if(tmp[0] != tmp[1] or tmp[1] != tmp[2]):
        print(tmp)
    
    mode = max(set(tmp), key=tmp.count)
    
    avg_pred.append(mode if mode else tmp[0])


result = accuracy_score(y_test,avg_pred)
print("Accuracy:",result)


Accuracy: 0.9555555555555556
